### ISSUE TITLE
Picking parameter - at run time 

### ISSUE THREAD

**Issue by kambojumang** [infinum/Retromock#18]
Picking parameter - at run time at @MockResponse {@Body = "{\"name\":\"John\", \"surname\":\"Smith\"}"} 

can that be change at run time. like: 

Api Request Model class
class User {
        @Json(name = "name")
        var name: String? = null
        @Json(name = "surname")
        var surname: String? = null

        override fun toString(): String {
            return ("User{"
                    + "name='" + name + '\''
                    + ", surname='" + surname + '\''
                    + '}')
        }
    }

public interface Service {
 @Mock
 @MockResponse(body = "{\"name\":\"John\", \"surname\":\"Smith\"}")
 @GET("/")
 Call<User> getUser(user: User);
}

can I mock using "user" object passing inside getUser(user: User), instead of @MockResponse(body = "{\"name\":\"John\", \"surname\":\"Smith\"}")

**Comment by ramanbedi1989** [comment]
Similar to #17.

**Comment by antunflas** [comment]
Hello @kambojumang,

I don't understand the proposal. What is the user object passed into the method? Retrofit doesn't support such things for get requests. Also, if you already have user object you would have to mock, you can just return it on the call side instead of executing this call. Am I missing something?

If this feature request is similar to as #17, please close this issue and let's continue in #17.

**Comment by antunflas** [comment]
Closing as it's the same as #17
